[settings]
experimental = true
legacy_version_file_disable_tools = ['java']
idiomatic_version_file_enable_tools = ["node"]

[tools]
chezmoi = "latest"
direnv = "2.32.2"
go = "1.25.1"
jq = "latest"
k6 = "0.54.0"
node = "22"
python = "3.12"
ripgrep = "12.1.1"
rust = "latest"
sccache = "latest"
zig = "0.11.0"
shellcheck = "latest"
shfmt = "latest"
uv = "latest"
yt-dlp = "latest"
yq = "latest"
"ubi:arxanas/git-branchless" = "latest"
neovim = "0.11.4"
lazygit = "latest"
"ubi:github/github-mcp-server" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
dasel = "latest"
ollama = "latest"
"ubi:nguyenvanduocit/rag-kit" = "latest"
"ubi:jj-vcs/jj" = "latest"
hurl = "latest"
"ubi:karust/openserp" = "0.5.3"
"npm:@bifrost_inc/superclaude" = "latest"
"npm:bwc-cli" = "latest"
"npm:claude-code-templates" = "latest"
rg = "latest"
